[package]
name = "monome-device"
version = "0.1.0"
edition = "2021"

[dependencies]
libmonome-sys = { path = "../libmonome-sys" }
url = "^2.5.3"

[dev-dependencies]
clap = { version = "^4.5.20", features = ["derive"] }